name: Windows Runner

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
      - name: Setup User
        run: net user runneradmin ${{ secrets.RDP_PASSWORD }}

      - name: Show Network Info
        run: ipconfig
